name: Build & Test

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@main

            - name: Set up Node.js
              uses: actions/setup-node@main
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build

    test:
        runs-on: ubuntu-latest
        needs: build # Depends on the build job
        steps:
            - name: Checkout code
              uses: actions/checkout@main

            - name: Set up Node.js
              uses: actions/setup-node@main
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Run Tests
              run: npm run test
